name: Build Multi-Platform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-suffix: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-suffix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            binary-suffix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-suffix: ""

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libxdo-dev

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
      working-directory: prc-editor-rust

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prc-editor-${{ matrix.target }}
        path: prc-editor-rust/target/${{ matrix.target }}/release/prc-editor-rust${{ matrix.binary-suffix }}
        if-no-files-found: error 