name: Build with Zig (Cross-compile)

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0

    - name: Install cargo-zigbuild
      run: cargo install cargo-zigbuild

    - name: Add targets
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-unknown-linux-gnu

    - name: Build Windows
      run: cargo zigbuild --release --target x86_64-pc-windows-gnu

    - name: Build macOS Intel
      run: cargo zigbuild --release --target x86_64-apple-darwin

    - name: Build macOS Apple Silicon
      run: cargo zigbuild --release --target aarch64-apple-darwin

    - name: Build Linux
      run: cargo zigbuild --release --target x86_64-unknown-linux-gnu

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: prc-editor-windows
        path: target/x86_64-pc-windows-gnu/release/prc-editor-rust.exe

    - name: Upload macOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        name: prc-editor-macos-intel
        path: target/x86_64-apple-darwin/release/prc-editor-rust

    - name: Upload macOS Apple Silicon artifact
      uses: actions/upload-artifact@v4
      with:
        name: prc-editor-macos-arm64
        path: target/aarch64-apple-darwin/release/prc-editor-rust

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: prc-editor-linux
        path: target/x86_64-unknown-linux-gnu/release/prc-editor-rust 